name: Deploy main on production

on:
  workflow_run:
    workflows: ["build-and-test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-main-on-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Call webhook to deploy main branch on production environment
        run: curl ${{ secrets.URL_WEBHOOK_DEPLOY_MAIN_ON_PRODUCTION }}
