name: Fix formatting with prettier

on:
  workflow_run:
    workflows: ["build-and-test"]
    branches: [staging]
    types:
      - completed

jobs:
  fix-formatting:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Format TS and TSX files with Prettier
        run: |
          npm i
          npm run format:fix
          git add .
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git commit -m "[auto] Format TS and TSX files with Prettier" || true
          git push -f
